{
  "test_name": "test_app_tearing_down_with_previous_exception",
  "test_file": "__internal__/_data/flask/tests/test_appctx.py",
  "static_methods": [
    "app.app_context",
    "cleanup_stuff.append",
    "Exception",
    "app.app_context"
  ],
  "dynamic_methods": [
    {
      "function": "app.app_context",
      "filename": "",
      "line": 0,
      "caller": "test_app_tearing_down_with_previous_exception"
    },
    {
      "function": "cleanup_stuff.append",
      "filename": "",
      "line": 0,
      "caller": "test_app_tearing_down_with_previous_exception"
    },
    {
      "function": "Exception",
      "filename": "",
      "line": 0,
      "caller": "test_app_tearing_down_with_previous_exception"
    },
    {
      "function": "app.app_context",
      "filename": "",
      "line": 0,
      "caller": "test_app_tearing_down_with_previous_exception"
    }
  ],
  "assertions": [
    "assert cleanup_stuff == [None]"
  ],
  "mocks": [],
  "success": true
}